# This file defines the Persistent Volume Claim for the PostgreSQL database, which requests 1Gi of storage.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi