# This config map is used to store application configuration settings for the IMC Tracker application.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: imc_db
  JWT_ACCESS_TOKEN_EXPIRES: "86400"
  FLASK_APP: "app.py"
  FLASK_ENV: "production"